// JsFromRoutes CacheKey 8ba17f24816548c7d5a3c7d05307b056
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  list: definePathHelper('get', '/'),
  terms: definePathHelper('get', '/terms'),
  privacy: definePathHelper('get', '/privacy'),
  faq: definePathHelper('get', '/faq'),
}
